### PR TITLE
Create about_us_code.html

### PR DESCRIPTION
**Pull request by vader22a**
This my HTML code for About Us page
which consist of :
contributor name
link of this repo
Instagram ID
Linkedin ID

### CODE REVIEW

**Review by acash1809 — APPROVED** [review]
good @vader22a

**Comment by acash1809** [comment]
@vader22a  ur from abes? branch & year?

**Comment by vader22a** [comment]
2nd year EC Branch

**Comment by acash1809** [comment]
ok 👍

**Pull request merged**
