### PR TITLE
leetcode problem 09

### PR DESCRIPTION
**Pull request by abhishek-mishra019**
Signed-off-by: Abhishek Mishra [am1426620@gmail.com](mailto:am1426620@gmail.com)
### Functionality:
to solve the pallindrome Problem in leetcode , Problem 09

### Solution:
solution with 15 lines of code with 31ms runtime in C
### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
paste the solution in leetcode problem 09 with C language and submit, check the runtime

### CODE REVIEW

**Comment by i-aka5h** [comment]
We are not accepting DSA problems right now

**Comment by abhishek-mishra019** [comment]
if i upload Portfolio website code, will you merge that?

**Comment by i-aka5h** [comment]
@abhishek-mishra019 sure, I will. Make sure you create a new directory named Portfolio and put your project under that directory.

**Comment by abhishek-mishra019** [comment]
okay sure

**Comment by abhishek-mishra019** [comment]
can you please unspam these pr, i actually didn't knew that dsa problems
arent allowed and got disqualified, it will be a great help

**Comment by abhishek-mishra019** [comment]
are you there bro? please mark it unspam :)
I've many PRs for dsa problems but they weren't marked spam, please don't
mark mine too

**Comment by abhishek-mishra019** [comment]
ive seen*

**Comment by i-aka5h** [comment]
No worries, I'll unmark them. And follow the guidelines from now on.

**Comment by acash1809** [comment]
@abhishek-mishra019 ive removed the spam label
@i-aka5h first try to give them a warning if they do not follow then mark them spam because a lot of beginners are participating in Hacktoberfest and they might make some mistake and its our reponsibility to guide them properly.

**Comment by abhishek-mishra019** [comment]
Will do, thanks!

**Comment by i-aka5h** [comment]
@acash1809 ok sir :)

**Comment by abhishek-mishra019** [comment]
Thanks a lot.

**Pull request closed without merging**
