### PR TITLE
Resolved issue #74

### PR DESCRIPTION
**Pull request by Brianrmendes**
Added the face detection code
@i-aka5h the project is located at Projects/Python/FaceDetection.py

### CODE REVIEW

**Review by i-aka5h — CHANGES_REQUESTED** [review]
Inadequate, Brian your program is missing files that are being used in the program.

**Comment by Brianrmendes** [comment]
I have added the image of the face, please check

**Review by i-aka5h — CHANGES_REQUESTED** [review]
Please add xml file as well.

**Comment by Brianrmendes** [comment]
Done

**Pull request merged**
